import './globals.css'
import { Lato } from 'next/font/google'

const lato = Lato({ subsets: ['latin', 'latin-ext'], weight: ['300', '400', '700', '900'] })

export const metadata = {
  title: 'iactive.pro test task',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={lato.className}>{children}</body>
    </html>
  )
}
